In [1]:
student1 = [69, 78, 72, 91, 85]
student2 = [75, 92, 92, 76, 92]

for i in range(len(student1)):
    scores = student1[i] + student2[i]
    print(scores)
    print("===============")

144
170
164
167
177


In [7]:
student1 = [69, 78, 72, 91, 85]
student2 = [75, 92, 92, 76, 92]

student1 + student2

[69, 78, 72, 91, 85, 75, 92, 92, 76, 92]

In [8]:
import numpy as np

In [4]:
import numpy as np
from numpy import ndarray
student1:ndarray = np.array([69, 78, 72, 91, 85])
print(type(student1))
student2:ndarray = np.array([75, 92, 92, 76, 92])
print(student2)  
print("===============")

#可以做陣列運算,不需使用for...in
print(student1 + student2)
totals:ndarray = student1 + student2
for total in totals:
    print(total)
    print("=========")


<class 'numpy.ndarray'>
[75 92 92 76 92]
[144 170 164 167 177]
144
170
164
167
177


In [13]:
array:ndarray = np.array([[1,2,3],[4,5,6]])
print(array)
#property
#ndim,shape,size,dtype
#維度,形狀,數量,類型

print(array.ndim)
print(array.shape)
print(array.size)
print(array.dtype)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int64


In [14]:
np.random.randint(50,101,size=(50, 5))

array([[ 62,  60,  53,  56,  59],
       [ 87,  54,  57,  78,  52],
       [ 88,  86,  86,  93,  56],
       [ 65,  72,  79,  57,  89],
       [ 86,  88,  59,  65,  76],
       [ 64,  58,  86,  59,  51],
       [ 89,  95,  57,  79,  64],
       [100,  95,  73,  58,  60],
       [ 58,  63,  85,  83,  74],
       [ 85,  72,  68,  73,  96],
       [ 64,  85,  83,  67,  52],
       [ 77, 100,  71,  59,  87],
       [ 98,  62,  62,  86,  65],
       [ 50,  53,  81,  72,  54],
       [ 68,  62,  60,  81,  97],
       [ 60,  84,  54,  52,  64],
       [ 69,  80,  93,  87,  98],
       [ 55,  67,  82,  54,  93],
       [ 56,  69,  97,  52,  61],
       [ 86,  72,  50,  81,  77],
       [ 50,  65,  92,  60,  64],
       [ 93,  59,  99,  84,  91],
       [ 96,  61,  54,  51,  51],
       [ 80,  69,  84,  55,  51],
       [ 86,  63,  83,  63,  64],
       [ 97,  95,  63,  94,  77],
       [ 89,  89,  99, 100,  66],
       [ 76,  91,  84,  75,  58],
       [ 71,  73,  67,  80,  67],
       [ 57,  